# Requiere modulos Apache:
# a2enmod proxy proxy_http headers ssl

<VirtualHost *:80>
  ServerName jardini.mi-registro.cl

  ProxyPreserveHost On
  ProxyPass / http://127.0.0.1:3009/
  ProxyPassReverse / http://127.0.0.1:3009/

  RequestHeader set X-Forwarded-Proto "http"
</VirtualHost>

<VirtualHost *:443>
  ServerName jardini.mi-registro.cl

  SSLEngine on
  SSLCertificateFile /ruta/a/cert.pem
  SSLCertificateKeyFile /ruta/a/key.pem
  # Si tienes cadena intermedia:
  # SSLCertificateChainFile /ruta/a/chain.pem

  ProxyPreserveHost On
  ProxyPass / http://127.0.0.1:3009/
  ProxyPassReverse / http://127.0.0.1:3009/

  RequestHeader set X-Forwarded-Proto "https"
</VirtualHost>
